name: Dependency & Security Check

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    name: Dependency Vulnerabilities
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        directory: ['./backend', './frontend/frontend']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci
      working-directory: ${{ matrix.directory }}

    - name: Run npm audit
      run: npm audit --audit-level=high
      working-directory: ${{ matrix.directory }}
      continue-on-error: true

    - name: Run npm audit fix (if possible)
      run: npm audit fix
      working-directory: ${{ matrix.directory }}
      continue-on-error: true

    - name: Check for dependency updates
      run: npx npm-check-updates --target minor
      working-directory: ${{ matrix.directory }}
      continue-on-error: true

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  license-check:
    name: License Compliance
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install license checker
      run: npm install -g license-checker

    - name: Check backend licenses
      run: |
        cd backend
        npm ci
        license-checker --onlyAllow 'MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause;CC0-1.0;Unlicense' --summary
      continue-on-error: true

    - name: Check frontend licenses
      run: |
        cd frontend/frontend
        npm ci
        license-checker --onlyAllow 'MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause;CC0-1.0;Unlicense' --summary
      continue-on-error: true